dbHost = 10.38.29.3
OUTPUT_PATH = //Fedyukov_AA//ARC$//Gorizont_Urup//Passport//
Put =  //Fedyukov_AA//ARC$//Gorizont_Urup//Image
##mi komp
#dbHost =  192.168.0.102
#dbHost = localhost
#OUTPUT_PATH = C://Gorizont_Urup//Passport//
#Put = C://Gorizont_Urup//Image//
#dbHost = 10.87.9.80
#OUTPUT_PATH =//fs01//OBMENNIK//GORIZONT//Passport//
#Put = //fs01//OBMENNIK//GORIZONT//Image
#dbHost = localhost
#OUTPUT_PATH = D://GORIONT_AK//Passport//
#Put = D://GORIONT_AK//Image